apiVersion: v1
kind: Pod
metadata:
  name: health-checker
spec:
  restartPolicy: Never
  containers:
    - name: health-checker
      image: us-central1-docker.pkg.dev/molten-verve-216720/antithesis-pdev-repository/etcd-health-checker:k8s
      imagePullPolicy: IfNotPresent
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
